# Запрашивает все публикации
GET http://localhost:3000/api/articles HTTP/1.1

###

# Запрашивает публикацию по :articleId
GET http://localhost:3000/api/articles/R_n-aW HTTP/1.1

###

# Добавление новой публикации
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
 "key": "value"
}

###

# Обновление публикации по :articleId
PUT http://localhost:3000/api/articles/R_n-aW HTTP/1.1
Content-Type: application/json

{
 "key": "value"
}

###

# Удаление объявления по :articleId
DELETE http://localhost:3000/api/articles/R_n-aW HTTP/1.1

###

# Список категорий
GET http://localhost:3000/api/categories HTTP/1.1

###

# Поиск публикаций по заголовкам
GET http://localhost:3000/api/search?query=Play HTTP/1.1

###

# Запрашивет список комментариев к публикации c :articleId
GET http://localhost:3000/api/articles/R_n-aW/comments HTTP/1.1

###

# Удаляет комментарий c :commentId из публикации c :articleId
DELETE http://localhost:3000/api/articles/R_n-aW/comments/MY5bSv HTTP/1.1

###

# Добавляет новый комментарий к публикации c :articleId
POST http://localhost:3000/api/articles/R_n-aW/comments HTTP/1.1
Content-Type: application/json

{
  "key": "value"
}
